version: '3'
services:
  postgresql:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stomp
  backend:
    image: cosmoskey/jsockets
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  frontend:
    image: cosmoskey/echats
    ports:
      - "3000:3000"
    depends_on:
      - backend
